### ISSUE TITLE
this needs gh pages

### ISSUE THREAD

**Issue by Happypizza** [Chameleon24/UZIPO#1]
to be a gallery of artwork using tasteful fonts 
[this](https://pages.github.com/) is github pages

**Comment by Chameleon24** [comment]
Okay, I'm doing it.

**Comment by Happypizza** [comment]
Is it done?

**Comment by Chameleon24** [comment]
No. Help pls.

**Comment by Happypizza** [comment]
What do you need help with?

**Comment by Chameleon24** [comment]
I made a Chameleon24.github.io but I don't know if I can make an
UZIPO.github.io.

**Comment by Happypizza** [comment]
You need to make a branch of this repo called gh-pages. In that repo, create a file called index.html. You need an index.html on Chameleon24.github.io too.

**Comment by Chameleon24** [comment]
Okay! I did that.

**Comment by Happypizza** [comment]
I'll check it out.

**Comment by Happypizza** [comment]
It works! Closing.
